language: cpp
sudo: required

addons:
  apt:
    update: true
    sources:
      - sourceline: 'ppa:jonathonf/gcc'
    packages:
      - gcc-8
      - libncurses5-dev
      - libncursesw5-dev

env:
  global:
    - MAKEFLAGS="-j 4"
    - CXX="g++-8"
    - CC="gcc-8"

matrix:
  include:
    - os: linux
      compiler: gcc-8
      env: "Build binaries"
      script:
        - /usr/local/bin/cmake -H. -Bbuild -DCMAKE_BUILD_TYPE=Release -DTRAVIS_BUILD=1
        - /usr/local/bin/cmake --build build
        - /usr/local/bin/cmake --build build --target roguelike

    - os: linux
      compiler: gcc-8
      env: "Code coverage"
      script:
        - /usr/local/bin/cmake -H. -Bbuild -DCMAKE_BUILD_TYPE=Debug -DTRAVIS_BUILD=1
        - /usr/local/bin/cmake --build build
        - /usr/local/bin/cmake --build build --target roguelike-tests
      after_success:
        - bash <(curl -s https://codecov.io/bash)

before_install:
  - export CXX="g++-8"
  - export CC="gcc-8"

install:
  - wget https://github.com/Kitware/CMake/releases/download/v3.13.4/cmake-3.13.4-Linux-x86_64.sh
  - sudo sh cmake-3.13.4-Linux-x86_64.sh --skip-license --prefix=/usr/local --exclude-subdir
  - git clone https://github.com/catchorg/Catch2.git
  - pushd Catch2
  - /usr/local/bin/cmake -Bbuild -H. -DBUILD_TESTING=OFF
  - sudo /usr/local/bin/cmake --build build/ --target install
  - popd



