language: cpp
sudo: required
addons:
  apt:
    update: true
    sources:
    - sourceline: ppa:ubuntu-toolchain-r/test
    - sourceline: ppa:jonathonf/binutils
    packages:
    - gcc-8
    - g++-8
    - libncurses5-dev
    - libncursesw5-dev
env:
  global:
  - MAKEFLAGS="-j 4"
  - CXX="g++-8"
  - CC="gcc-8"
matrix:
  include:
  - os: linux
    compiler: g++-8
    env: Build binaries (with ncurses)
    script:
    - "/usr/local/bin/cmake -H. -Bbuild -DCMAKE_BUILD_TYPE=Release -DGRAPHICS_LIB=ncurses
      -DTRAVIS_BUILD=1"
    - "/usr/local/bin/cmake --build build"
    - "/usr/local/bin/cmake --build build --target roguelike"
    - mv build/roguelike build/roguelike-$TRAVIS_TAG-ncurses
    deploy:
      provider: releases
      skip_cleanup: true
      api_key:
        secure: MxOLYJLu7Iph3whqLeKOvUhRqo2fkuysMpOwedCaVfMSwglVxX+zrVXt60rYO/iarv7D6YxQL5RM0XWe6CvVp7Jmu0/BddpEojyty7J1wx2xXpbLP1rjS+tWhXCia9BbIBNJdUXMwo4cQn/LbwnPFwSBqXl38Cv/NUYacZMhk/X55D72vHf4JkA395ixOqudH7qP0iUUc641terSpKei8uJqd1lMxEdzp5n+i5zHW5RTg+/sE3E6L412V7IJDuffoLV25SBK+Oh2b9KMRlzibvforE+To4CWH+EGTP1GFs6A0LhtcYblAqiL2nlAAwU7c6Zosbg++xac7VQFxb/0WjFG+CJMGIiHe2n3SXoTLi1A5nieQjbNJEVo6S00ILJD3Ml0yrVYlj4SCjx72ddfjXqfFGg1w8DZ3xnZqYiZG2PaF6uB1dbiVJ5tDXqB8OUQ6i5mHSh4O2sqIUFA7qMe4jyqYtra6st5jDHx8yXX7tfKN07ylchlVRI0fn8ql4jWF1H7MNUG4xoxuMbu2ub+lcdKUS7uY6QaBDXSHBkcKquuIQ8fSTxfYrNsDYydvRqBqeNuikUoqOz2ILXUf3B/hsow+89RZV8gRHEwHlsVwm/rQx6Q3mQlYUVFhodGhC9wLliwDqvYhru43ewQO8+TejapSocspnBBrnuoRHEYwzY=
      on:
        tags: true
        repo: t1meshift/roguelike
        file: build/roguelike-$TRAVIS_TAG-ncurses
  - os: linux
    compiler: g++-8
    env: Code coverage
    script:
    - "/usr/local/bin/cmake -H. -Bbuild -DCMAKE_BUILD_TYPE=Debug -DTRAVIS_BUILD=1"
    - "/usr/local/bin/cmake --build build"
    - "/usr/local/bin/cmake --build build --target roguelike-tests"
    - cd build
    - ctest --output-on-failure
    after_success:
    - bash <(curl -s https://codecov.io/bash)
before_install:
- sudo apt-get install -qq --yes --force-yes binutils
- export CXX="g++-8"
- export CC="gcc-8"
- export GCOV="gcov-8"
install:
- wget https://github.com/Kitware/CMake/releases/download/v3.13.4/cmake-3.13.4-Linux-x86_64.sh
- sudo sh cmake-3.13.4-Linux-x86_64.sh --skip-license --prefix=/usr/local --exclude-subdir
- git clone https://github.com/catchorg/Catch2.git
- pushd Catch2
- "/usr/local/bin/cmake -Bbuild -H. -DBUILD_TESTING=OFF"
- sudo /usr/local/bin/cmake --build build/ --target install
- popd
